_schema: _schema
source: src
paths:
  uploads: img/
collections_config:
  posts:
    path: blog
    icon: post
    description: Blog posts about all things under the sun
    _enabled_editors:
      - content
      - visual
    _inputs:
      tags:
        type: multiselect
        options:
          allow_create: true
          empty_type: array
          values: data.taglist
        cascade: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: .cloudcannon/schemas/post.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        icon: notes
  pages:
    path: pages
    icon: article
    filter: strict
    description: Fascinating pages of this 'ere website
    _enabled_editors:
      - visual
      - content
    _inputs:
      keywords:
        type: multiselect
        options:
          allow_create: true
          empty_type: array
          values:
            - music
            - media
            - personal
          value_key:
        cascade: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: .cloudcannon/schemas/page.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: true
        remove_extra_inputs: false
        icon: notes
  data:
    path: _data
    icon: settings_applications
    disable_url: true
    description: Metadata for site layouts and other data
    _enabled_editors:
      - data
    disable_add: true
    disable_add_folder: true
    disable_file_actions: false
_enabled_editors:
  - visual
  - content
  - data
_inputs:
  date:
    type: datetime
    instance_value: NOW
    cascade: true
  image_file:
    type: file
    options:
      resize_style: cover
    cascade: true
  layout:
    type: auto
    hidden: true
    cascade: true
  type:
    type: auto
    hidden: true
    cascade: true
  permalink:
    type: auto
    hidden: true
    cascade: true
_editables:
  text:
    allow_custom_markup: true
    remove_custom_markup: false
    bold: true
    italic: true
    redo: true
    removeformat: true
    underline: true
  block:
    allow_custom_markup: false
    remove_custom_markup: false
    blockquote: true
    bold: true
    bulletedlist: true
    code: true
    embed: true
    format: p h3
    horizontalrule: true
    image: true
    image_size_attributes: true
    italic: true
    numberedlist: true
    redo: true
    resize_style: contain
    snippet: true
    strike: true
    table: true
    underline: true
    undo: true
  content:
    allow_custom_markup: false
    remove_custom_markup: false
    blockquote: true
    bold: true
    bulletedlist: true
    center: align-center
    code: true
    copyformatting: true
    embed: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    horizontalrule: true
    image: true
    image_size_attributes: true
    indent: true
    italic: true
    justify: align-justify
    left: align-left
    link: true
    numberedlist: true
    outdent: true
    redo: true
    removeformat: true
    resize_style: contain
    right: align-right
    snippet: true
    strike: true
    styles: .cloudcannon/css/editor.css
    subscript: false
    superscript: false
    table: true
    underline: true
    undo: true
_snippets_imports:
  eleventy_liquid: true
_snippets:
  my_image_snippet:
    template: eleventy_liquid_shortcode_positional_args
    inline: false
    preview:
      text: Block image
    definitions:
      shortcode_name: image
      positional_args:
        - editor_key: Image
          type: string
        - editor_key: Alt
          type: string
    _inputs:
      Image:
        type: image
        cascade: true
      trim_bottom_left:
        type: auto
        hidden: true
        cascade: true
      trim_top_right:
        type: auto
        hidden: true
        cascade: true
      trim_bottom_right:
        type: auto
        hidden: true
        cascade: true
      trim_top_left:
        type: auto
        hidden: true
        cascade: true
      trim_left:
        type: auto
        hidden: true
        cascade: true
      trim_right:
        type: auto
        hidden: true
        cascade: true
  my_image_caption_snippet:
    template: eleventy_liquid_shortcode_positional_args
    inline: false
    preview:
      text: Block image with caption
    definitions:
      shortcode_name: image
      positional_args:
        - editor_key: Image
          type: string
        - editor_key: Alt
          type: string
        - editor_key: Caption
          type: string
    _inputs:
      Image:
        type: image
        cascade: true
      Caption:
        type: text
        cascade: true
      trim_bottom_left:
        type: auto
        hidden: true
        cascade: true
      trim_top_right:
        type: auto
        hidden: true
        cascade: true
      trim_bottom_right:
        type: auto
        hidden: true
        cascade: true
      trim_top_left:
        type: auto
        hidden: true
        cascade: true
      trim_left:
        type: auto
        hidden: true
        cascade: true
      trim_right:
        type: auto
        hidden: true
        cascade: true
  my_image_exif_snippet:
    template: eleventy_liquid_shortcode_positional_args
    inline: false
    preview:
      text: Block image with caption + EXIF
    definitions:
      shortcode_name: image
      positional_args:
        - editor_key: Image
          type: string
        - editor_key: Alt
          type: string
        - editor_key: Caption
          type: string
        - editor_key: Camera
          type: string
        - editor_key: Lens
          type: string
        - editor_key: Film
          type: string
        - editor_key: ISO
          type: string
    _inputs:
      Image:
        type: image
        cascade: true
      Caption:
        type: text
        cascade: true
      Camera:
        type: select
        options:
          values: data.camera
        cascade: true
      Lens:
        type: select
        options:
          values: data.lens
        cascade: true
      Film:
        type: select
        options:
          values: data.film
        cascade: true
      ISO:
        type: select
        options:
          values: data.iso
        cascade: true
      trim_bottom_left:
        type: auto
        hidden: true
        cascade: true
      trim_top_right:
        type: auto
        hidden: true
        cascade: true
      trim_bottom_right:
        type: auto
        hidden: true
        cascade: true
      trim_top_left:
        type: auto
        hidden: true
        cascade: true
      trim_left:
        type: auto
        hidden: true
        cascade: true
      trim_right:
        type: auto
        hidden: true
        cascade: true
  my_image_centered_snippet:
    template: eleventy_liquid_shortcode_positional_args
    inline: false
    preview:
      text: Centered image
    definitions:
      shortcode_name: image_centered
      positional_args:
        - editor_key: Image
          type: string
        - editor_key: Alt
          type: string
    _inputs:
      Image:
        type: image
        cascade: true
  my_bandcamp_snippet:
    template: eleventy_liquid_shortcode_positional_args
    inline: false
    preview:
      text: Bandcamp player
    definitions:
      shortcode_name: bandcamp
      positional_args:
        - editor_key: src
          type: string
    _inputs:
      src:
        type: url
        cascade: true
data_config:
  camera:
    path: _data/camera.yaml
  lens:
    path: _data/lens.yaml
  film:
    path: _data/film.yaml
  iso:
    path: _data/iso.yaml
  taglist:
    path: _data/taglist.yaml
timezone: Pacific/Auckland
markdown:
  engine:
  options:
