source: src
paths:
  uploads: _11ty/_static/img/
  static: _11ty/_static/
  collections:
  data: _11ty/_data/
  layouts: _11ty/_layouts/
  includes: _11ty/_includes/
collections_config:
  posts:
    path: blog
    output: true
    description: Blog posts about all things under the sun
    icon: post
    preview:
      text:
      subtext:
      icon:
      icon_color:
      image:
      metadata:
      gallery:
    _editables: {}
    _enabled_editors:
      - content
      - visual
    _inputs:
      tags:
        type: multiselect
        options:
          allow_create: true
          empty_type: array
          values:
            - post
            - music
            - social media
            - tumblr
            - vespa
          value_key:
        cascade: true
      published:
        type: switch
        cascade: true
    _select_data: {}
    _structures: {}
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: .cloudcannon/schemas/post.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        icon: notes
  pages:
    path: pages
    output: true
    filter: strict
    description: Fascinating pages of this 'ere website
    icon: article
    preview:
      text:
      subtext:
      icon:
      icon_color:
      image:
      metadata:
      gallery:
    _editables: {}
    _enabled_editors:
      - visual
      - content
    _inputs:
      keywords:
        type: multiselect
        options:
          allow_create: true
          empty_type: array
          values:
            - music
            - media
            - personal
          value_key:
        cascade: true
    _select_data: {}
    _structures: {}
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: .cloudcannon/schemas/page.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: true
        remove_extra_inputs: false
        icon: notes
  data:
    path: _11ty/_data
    output: false
    description: Metadata for site layouts and other data
    icon: settings_applications
    _enabled_editors:
      - data
    disable_add: true
    disable_add_folder: true
    disable_file_actions: false
collections_config_override: false
_enabled_editors:
  - visual
  - content
  - data
_inputs:
  date:
    type: datetime
    instance_value: NOW
    cascade: true
  image_file:
    type: file
    options:
      width: 700
      resize_style: cover
_select_data: {}
_structures: {}
_editables:
  text:
    italic: true
  block:
    format: p h3
    image_size_attributes: true
    redo: true
    undo: true
  content:
    blockquote: true
    bold: true
    bulletedlist: true
    center: align-center
    code: true
    copyformatting: true
    embed: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    horizontalrule: true
    image: true
    image_size_attributes: true
    indent: true
    italic: true
    justify: align-justify
    left: align-left
    link: true
    numberedlist: true
    outdent: true
    redo: true
    removeformat: true
    right: align-right
    snippet: true
    strike: true
    subscript: false
    superscript: false
    table: true
    underline: true
    undo: true
data_config: {}
timezone: Pacific/Auckland
_snippets_imports:
  eleventy_liquid: true
