# Read the CloudCannon documentation for more information on how to use this file:
# https://cloudcannon.com/documentation/articles/setting-global-configuration/?ssg=Eleventy

# Collections are related sets of content files, typically grouped by folder.
# Here you can define your collections, as well as any
# CloudCannon configuration specific to those collections.
collections_config:
  posts:
    path: blog
    output: true
    _enabled_editors:
      - visual
      - content
    schemas:
      default:
        path: _11ty/_layouts/article.njk
  pages:
    path: pages
    output: true
    filter: strict
    _enabled_editors:
      - visual
      - content
    schemas:
      default:
        path: _11ty/_layouts/page.njk
  # data:
  #  path: _11ty/_includes
  #  output: false

# Control which collections are displayed in the CloudCannon site navigation,
# and how those collections are grouped.
collection_groups:


# Set this to true to disable auto-detection of collections.
collections_config_override: false

# Control which data sets are available to populate select and multiselect inputs.
data_config:

# Base path to your source files, relative to the root folder of your repository.
source: src


# The locations of various types of files within your site.
# Each path is relative to your site's source folder.
paths:
  data: _11ty/_data/
  collections: 
  layouts: _11ty/_layouts/
  static: _11ty/_static/
  uploads: _11ty/_static/img/
  includes: _11ty/_includes/
  pages: pages

# Lets you control the look and behaviour of the Source Editor.
source_editor:

# Timezone of your site in IANA format. This is used by date and datetime inputs
# within the CloudCannon Data Editor.
timezone: NZST
