#!/bin/bash

npx -y pagefind --site public

if [ "$ELEVENTY_ENV" = "production" ]; then
  npx html-minifier-terser --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --file-ext html --input-dir ./public --output-dir ./public
fi
