#!/bin/bash

npm exec jampack public
npx -y pagefind --site public
npx @bookshop/generate

# Check if the variable equals "production"
if [ "$ELEVENTY_ENV" = "production" ]; then
  html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --file-ext html --input-dir ./public --output-dir ./public
else
  echo "The variable is not equal to 'production'."
fi

