#!/bin/bash

npx -y pagefind --site public
npx @bookshop/generate

# Check if the variable equals "production"
if [ "$ELEVENTY_ENV" = "production" ]; then
  html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-js true ./public/*.html
else
  echo "The variable is not equal to 'production'."
fi