#!/bin/bash

npx tailwindcss -i src/_11ty/_tailwindCSS/raw-website.css -o public/css/style.css --minify
ELEVENTY_ENV=production npm install html-minifier -g
ELEVENTY_ENV=production html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype