language: en-NZ
lang: en
siteName: anaru.nz
shortName: Anaru
motto: Minimalist website about me
authorName: Andrew Long
siteDescription: Site built on CloudCannon and 11ty about Andrew Long
sitekeyword: Personal
creationDate: 2022-02-12T00:00:00Z
url: process.env.URL
robots: index, follow
themeColor: '#000000'
backgroundColor: '#000000'
mail: me@anaru.nz
telephone: ''
facebookUser: andrewlslong
githubUser: socialspacedev
linkedinkUser: andrewlslong
instagramUser: socialspace
lastfmUser: socialspace
threadsUser: '@socialspace'
bskyUser: socialspace
mastodonUser: socialspace
