language: en-GB
lang: en
siteName: anaru.nz
shortName: Anaru
motto: Minimalist website built on CloudCannon and 11ty.
authorName: Andrew Long
siteDescription: Home site for Andrew Long
sitekeyword: Personal
creationDate: 2022-02-12T00:00:00Z
url: ${process.env.URL || 'https://anaru.nz'}
robots: index, follow
themeColor: '#000000'
backgroundColor: '#000000'
mail: me@anaru.nz
telephone: ''
facebookUser: andrewlslong
githubUser: socialspacedev
linkedinkUser: andrewlslong
instagramUser: socialspace
lastfmUser: socialspace
threadsUser: '@socialspace'
bskyUser: socialspace
mastodonUser: socialspace
