spec:
  structures:
    - blocks
  label: "Text block"
  description: Text block of content.
  icon: description
  tags: ['content']

# Defines the structure of this component, as well as the default values
blueprint:
  text: "Add your heading and label text."

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
